name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Generate config.js
      run: |
        # Generar config.js directamente sin problemas de caracteres especiales
        cat > config.js << 'EOF'
        const CONFIG = {
            FORM_ENDPOINT: '${{ secrets.FORM_ENDPOINT }}',
            RECAPTCHA_SITE_KEY: '${{ secrets.RECAPTCHA_SITE_KEY || '' }}'
        };
        window.CONFIG = CONFIG;
        EOF
        
        # Verificar que se generó correctamente
        echo "Config generado:"
        cat config.js
        
    - name: Verify files are ready
      run: |
        # Verificar que tenemos todos los archivos necesarios
        echo "Archivos disponibles:"
        ls -la
        echo "Contenido de config.js:"
        head -n 10 config.js
        echo "index.html contiene config.js:"
        grep -n "config.js" index.html || echo "config.js ya está referenciado"
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 